### PR TITLE
cmake: mark headers as SYSTEM if not the top level project

### LINKED ISSUE #28: Non standalone builds should mark include files as SYSTEM
The binlog CMake target_include_directories call should detect when binlog is being compiled as part of another project and mark the include files as SYSTEM so that extra compiler warnings enabled by the parent project can't be triggered on the binlog header files.

Reasoning: The current convention in binlog of having constructor parameters named the same as private class members is causing compiler warnings for users who have -Wshadow enabled and breaking users who have both -Wshadow and -Werror enabled.

Example Fix: https://github.com/microsoft/GSL/blob/master/CMakeLists.txt#L58

### PR DESCRIPTION
**Pull request by erenon**
Fixes #28

### CODE REVIEW

**Comment by erenon** [comment]
@andrewkcorcoran : You are right. I gather at least two tests are needed: one that builds a CMake project, that includes Binlog in its source tree, and an other that builds a CMake project, that references a Binlog installation. While I'm working on it, I hope you can continue experimenting, as the Wshadow warnings are fixed.

**Comment by erenon** [comment]
@andrewkcorcoran : It should be good now

**Comment by andrewkcorcoran** [comment]
Great - the CMake changes suppress the shadow warnings now :)

However - when I tried to do a like for like comparison to the extra CMake tests you added I get the below error.

`CMake Error at source/utils/CMakeLists.txt:1 (add_library):
  Target "utils" links to target "binlog::binlog" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?`

It looks like you need to [add an alias](https://cliutils.gitlab.io/modern-cmake/chapters/install.html) to your CMake setup (perhaps this should be a separate issue to track?). The worrying thing is I don't understand why your tests are passing but I get the above error? :/

**Comment by erenon** [comment]
Can you post your full cmake file, and a short repro? Also see how to the
test invokes cmake, with the extra envvar pointing at the install dir (not
the source dir).

**Comment by erenon** [comment]
(the shadow warnings were fixed previously, this change does not suppress them - but I checked the command line, and now -isystem is being used.)

**Comment by andrewkcorcoran** [comment]
`  project(test)

  add_subdirectory(binlog)
  add_executable(test main.cpp)
  target_link_libraries(test binlog::binlog)`

Perhaps the export needs to be cleared between CI runs and the subdir test is picking up the export from the install test?

**Comment by erenon** [comment]
@andrewkcorcoran : if `add_subdirectory` is used, `binlog` must be linked, not `binlog::binlog`, as `add_subdirectory` does not add a namespace. See the difference between the two test `CMakeLists.txt` files in this change.

To make `binlog::binlog` work, you'll need to call `find_package`, as shown in:
https://github.com/Morgan-Stanley/binlog/pull/34/files#diff-ee59ba674112481d62952abb3b7fc0f7

**Comment by andrewkcorcoran** [comment]
@erenon Ah I hadn't noticed the difference in usage between subdirectory and install, that explains why my test was failing.

I believe the recommendation is to mimic namespaces in `add_subdirectory` usage [with `add_library(binlog::binlog ALIAS binlog)`](url). That way the linking command between install and subdirectory users is the same.

**Comment by erenon** [comment]
Alias targets were added, and the test was updated. Now the add_subdirectory usage is consistent with find_package (binlog::binlog and binlog::headers)

**Pull request merged**
